import {
  SolongWalletAdapter,
  PhantomWalletAdapter,
  SolflareWalletAdapter,
  SkyWalletAdapter,
  MathWalletAdapter,
  NekoWalletAdapter,
  NufiWalletAdapter,
  OntoWalletAdapter,
  SpotWalletAdapter,
  TrustWalletAdapter,
  AlphaWalletAdapter,
  AvanaWalletAdapter,
  HuobiWalletAdapter,
  SaifuWalletAdapter,
  TorusWalletAdapter,
  BitgetWalletAdapter,
  BitpieWalletAdapter,
  CloverWalletAdapter,
  LedgerWalletAdapter,
  SalmonWalletAdapter,
  TrezorWalletAdapter,
  CoinhubWalletAdapter,
  FractalWalletAdapter,
  KrystalWalletAdapter,
  NightlyWalletAdapter,
  SafePalWalletAdapter,
  CoinbaseWalletAdapter,
  HyperPayWalletAdapter,
  KeystoneWalletAdapter,
} from "@solana/wallet-adapter-wallets";
import { Adapter } from "@jup-ag/wallet-adapter";

const arr: Adapter[] = [
  new SolongWalletAdapter(),
  new PhantomWalletAdapter(),
  new SolflareWalletAdapter(),
  new SkyWalletAdapter(),
  new NekoWalletAdapter(),
  new NufiWalletAdapter(),
  new OntoWalletAdapter(),
  new SpotWalletAdapter(),
  new TrustWalletAdapter(),
  new AlphaWalletAdapter(),
  new AvanaWalletAdapter(),
  new HuobiWalletAdapter(),
  new SaifuWalletAdapter(),
  new TorusWalletAdapter(),
  new BitgetWalletAdapter(),
  new BitpieWalletAdapter(),
  new CloverWalletAdapter(),
  new LedgerWalletAdapter(),
  new SalmonWalletAdapter(),
  new TrezorWalletAdapter(),
  new CoinhubWalletAdapter(),
  new FractalWalletAdapter(),
  new KrystalWalletAdapter(),
  new NightlyWalletAdapter(),
  new SafePalWalletAdapter(),
  new CoinbaseWalletAdapter(),
  new HyperPayWalletAdapter(),
  new KeystoneWalletAdapter()
];

export default arr;
